from setuptools import setup, find_packages

setup(
    name="nullsec-freakshow",
    version="3.1.0",
    description="🎪 The Freakshow Suite — 40 Weird & Creepy Security Tools in 9 Languages + Python Fallback Ports",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    author="bad-antics",
    author_email="nullsec@proton.me",
    url="https://github.com/bad-antics/nullsec-freakshow",
    packages=find_packages(),
    python_requires=">=3.10",
    install_requires=[
        "click>=8.0",
        # ── Python tools (pip-installable) ──
        "nullsec-sigil>=1.0.0",
        "nullsec-dead-drop>=1.0.0",
        "nullsec-miasma>=1.0.0",
        "nullsec-temporal>=1.0.0",
        "nullsec-hexspeak>=1.0.0",
        "nullsec-whisper>=1.0.0",
        "nullsec-skinwalker>=1.0.0",
        "nullsec-ouija>=1.0.0",
        "nullsec-eidolon>=1.0.0",
        "nullsec-doppelganger>=1.0.0",
        "nullsec-seance>=1.0.0",
        "nullsec-lamprey>=1.0.0",
        "nullsec-voodoo>=1.0.0",
        "nullsec-cryptid>=1.0.0",
        "nullsec-gremlin>=1.0.0",
        "nullsec-grimoire>=1.0.0",
        "nullsec-wendigo>=1.0.0",
        "nullsec-harbinger>=1.0.0",
        "nullsec-revenant>=1.0.0",
        "nullsec-necronomicon>=1.0.0",
        "nullsec-chimera>=1.0.0",
        "nullsec-basilisk>=1.0.0",
        "nullsec-apparition>=1.0.0",
        "nullsec-manticore>=1.0.0",
        "nullsec-ghoul>=1.0.0",
        "nullsec-lich>=1.0.0",
        "nullsec-imp>=1.0.0",
        "nullsec-shade>=1.0.0",
        "nullsec-djinn>=1.0.0",
        "nullsec-mothman>=1.0.0",
        "nullsec-yokai>=1.0.0",
        # ── Python fallback ports for multi-language tools ──
        "nullsec-wraith-py>=1.0.0",
        "nullsec-banshee-py>=1.0.0",
        "nullsec-poltergeist-py>=1.0.0",
        "nullsec-kobold-py>=1.0.0",
        "nullsec-specter-py>=1.0.0",
        "nullsec-changeling-py>=1.0.0",
        "nullsec-familiar-py>=1.0.0",
        "nullsec-golem-py>=1.0.0",
        "nullsec-phantom-py>=1.0.0",
        # Non-Python native tools (wraith, banshee, poltergeist, kobold,
        # specter, changeling, familiar, golem, phantom) require their
        # respective compilers/runtimes — see README.
    ],
    entry_points={
        "console_scripts": [
            "freakshow=freakshow.cli:entry_point",
        ],
    },
)
